# ATC_CODE_EXTRACTION_NOTEBOOK

In [11]:
import pandas as pd
import re

# Read the Excel file
df_antimicrobials_ATC = pd.read_excel('C:\\Personal_Projects\\Astro\\project_resources\\Completed_Data_Tables_withVersions\\Antimicrobials_with_ATC_COMPLETE.xlsx', sheet_name='Sheet1')

# Display the first 5 rows
df_antimicrobials_ATC.head()

,ATC_CODE,WHONET_CODE,ANTIMICROBIAL,ANTIMICROBIAL_CLASS,WHO_AWARE_CLASSIFICATION
0,NaN,FCT,5-Fluorocytosine,NaN,NaN
1,NaN,ACM,Acetylmidecamycin,NaN,NaN
2,NaN,ASP,Acetylspiramycin,NaN,NaN
3,D06AX12,AMK,Amikacin,NaN,NaN
4,D06AX12,AKF,Amikacin/Fosfomycin,NaN,NaN

In [12]:
#Read WHO_EML list
df_who_eml_Workbook = pd.read_excel('C:\\Personal_Projects\\Astro\\project_resources\\WHO_EML.xlsx')
df_who_eml_ALL = pd.read_excel('C:\\Personal_Projects\\Astro\\project_resources\\WHO_EML.xlsx', sheet_name='AWaRe classification 2023')
who_eml_Access = pd.read_excel('C:\\Personal_Projects\\Astro\\project_resources\\WHO_EML.xlsx', sheet_name='Access')
who_eml_Watch = pd.read_excel('C:\\Personal_Projects\\Astro\\project_resources\\WHO_EML.xlsx', sheet_name='Watch')
who_eml_Reserve = pd.read_excel('C:\\Personal_Projects\\Astro\\project_resources\\WHO_EML.xlsx', sheet_name='Reserve')

In [9]:
# Check WHO EML workbook content with error handling
try:
    print("WHO EML Workbook Info:")
    print("-" * 50)
    print(df_who_eml_Workbook.info())
    print("\nFirst 5 rows:")
    display(df_who_eml_Workbook.head())
except Exception as e:
    print(f"Error accessing DataFrame: {str(e)}")
    
# Also check the other WHO EML dataframes
print("\nOther WHO EML DataFrames:")
print("-" * 50)
for name, df in [('AWaRe classification 2023', df_who_eml_ALL),
                ('Access', who_eml_Access),
                ('Watch', who_eml_Watch),
                ('Reserve', who_eml_Reserve)]:
    print(f"\n{name} sheet:")
    print(f"Shape: {df.shape}")
    print("First row:")
    display(df.head(1))

WHO EML Workbook Info:
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
None

First 5 rows:

Empty DataFrame
Columns: []
Index: []

Other WHO EML DataFrames:
--------------------------------------------------

AWaRe classification 2023 sheet:
Shape: (260, 8)
First row:

,"WHO Access, Watch, Reserve (AWaRe) classification of antibiotics for evaluation and monitoring of use, 2023",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,This classification is intended to be used as ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Access sheet:
Shape: (90, 5)
First row:

,Access group antibiotics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,This group includes antibiotics that have acti...,NaN,NaN,NaN,NaN

Watch sheet:
Shape: (144, 5)
First row:

,Watch group antibiotics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,This group includes antibiotic classes that ha...,NaN,NaN,NaN,NaN

Reserve sheet:
Shape: (32, 5)
First row:

,Reserve group antibiotics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,This group includes antibiotics and antibiotic...,NaN,NaN,NaN,NaN

## WHO EML Workbook Analysis
Let's examine the structure and contents of the WHO Essential Medicines List workbook.

In [7]:
# Display basic information about the DataFrame
print("DataFrame Info:")
print("-" * 50)
print(df_who_eml_Workbook.info())

print("\nFirst few rows:")
print("-" * 50)
display(df_who_eml_Workbook.head())

print("\nColumn names:")
print("-" * 50)
print(df_who_eml_Workbook.columns.tolist())

print("\nDataFrame shape:")
print("-" * 50)
print(f"Rows: {df_who_eml_Workbook.shape[0]}")
print(f"Columns: {df_who_eml_Workbook.shape[1]}")

DataFrame Info:
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
None

First few rows:
--------------------------------------------------

Empty DataFrame
Columns: []
Index: []

Column names:
--------------------------------------------------
[]

DataFrame shape:
--------------------------------------------------
Rows: 0
Columns: 0

In [ ]:
# Analyze key columns if they exist
for col in df_who_eml_Workbook.columns:
    if df_who_eml_Workbook[col].dtype == 'object':
        print(f"\nUnique values in {col}:")
        print("-" * 50)
        print(df_who_eml_Workbook[col].value_counts().head())
        print(f"Total unique values: {df_who_eml_Workbook[col].nunique()}")
        print()

In [10]:
# Analyze AWaRe classification sheet in detail
print("AWaRe Classification Analysis:")
print("-" * 50)
print("\nColumns:")
print(df_who_eml_ALL.columns.tolist())

# Skip the first row which contains description
df_aware = df_who_eml_ALL.iloc[1:].copy()
print("\nSample of actual antibiotic entries:")
display(df_aware.head())

# Count antibiotics by classification
print("\nDistribution of antibiotics by AWaRe classification:")
for col in df_aware.columns:
    if not col.startswith('Unnamed'):
        values = df_aware[col].value_counts()
        print(f"\n{col}:")
        print(values)

AWaRe Classification Analysis:
--------------------------------------------------

Columns:
['WHO Access, Watch, Reserve (AWaRe) classification of antibiotics for evaluation and monitoring of use, 2023', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

Sample of actual antibiotic entries:

,"WHO Access, Watch, Reserve (AWaRe) classification of antibiotics for evaluation and monitoring of use, 2023",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Antibiotic,Class,ATC code,Category,Listed on EML/EMLc 2023,NaN,NaN,NaN
3,Amikacin,Aminoglycosides,J01GB06,Access,Yes,NaN,NaN,NaN
4,Amoxicillin,Penicillins,J01CA04,Access,Yes,NaN,NaN,NaN
5,Amoxicillin/clavulanic-acid,Beta-lactam/beta-lactamase-inhibitor,J01CR02,Access,Yes,NaN,NaN,NaN

Distribution of antibiotics by AWaRe classification:

WHO Access, Watch, Reserve (AWaRe) classification of antibiotics for evaluation and monitoring of use, 2023:
WHO Access, Watch, Reserve (AWaRe) classification of antibiotics for evaluation and monitoring of use, 2023
Antibiotic         1
Roxithromycin      1
Oxytetracycline    1
Panipenem          1
Pazufloxacin       1
                  ..
Doripenem          1
Doxycycline        1
Enoxacin           1
Epicillin          1
Vancomycin_oral    1
Name: count, Length: 258, dtype: int64

## Data Validation and Update Process
Let's validate the ATC codes and add WHO AWARE Classification and Antimicrobial Class information.

In [13]:
# Load the completed antimicrobials data
print("Loading antimicrobials data...")
df_completed = pd.read_excel('C:\\Personal_Projects\\Astro\\project_resources\\Completed_Data_Tables_withVersions\\Antimicrobials_with_ATC_COMPLETE.xlsx')
print(f"Loaded {len(df_completed)} antimicrobials")

# Clean up WHO EML data - skip the description rows and reset index
df_who_eml_clean = df_who_eml_ALL.iloc[2:].copy()  # Skip first two rows
df_who_eml_clean.columns = ['Antibiotic', 'Class', 'ATC_code', 'Category', 'Listed_on_EML', 'Unnamed_5', 'Unnamed_6', 'Unnamed_7']
df_who_eml_clean = df_who_eml_clean.reset_index(drop=True)

print("\nWHO EML data shape:", df_who_eml_clean.shape)
print("\nSample of WHO EML data:")
display(df_who_eml_clean.head())

Loading antimicrobials data...
Loaded 392 antimicrobials

WHO EML data shape: (258, 8)

Sample of WHO EML data:

,Antibiotic,Class,ATC_code,Category,Listed_on_EML,Unnamed_5,Unnamed_6,Unnamed_7
0,Antibiotic,Class,ATC code,Category,Listed on EML/EMLc 2023,NaN,NaN,NaN
1,Amikacin,Aminoglycosides,J01GB06,Access,Yes,NaN,NaN,NaN
2,Amoxicillin,Penicillins,J01CA04,Access,Yes,NaN,NaN,NaN
3,Amoxicillin/clavulanic-acid,Beta-lactam/beta-lactamase-inhibitor,J01CR02,Access,Yes,NaN,NaN,NaN
4,Ampicillin,Penicillins,J01CA01,Access,Yes,NaN,NaN,NaN

In [14]:
# Create mapping dictionaries from WHO EML data
atc_to_class = dict(zip(df_who_eml_clean['ATC_code'], df_who_eml_clean['Class']))
atc_to_category = dict(zip(df_who_eml_clean['ATC_code'], df_who_eml_clean['Category']))
name_to_class = dict(zip(df_who_eml_clean['Antibiotic'].str.lower(), df_who_eml_clean['Class']))
name_to_category = dict(zip(df_who_eml_clean['Antibiotic'].str.lower(), df_who_eml_clean['Category']))

# Function to find best match for antibiotic name
def find_matching_antibiotic(name):
    name_lower = name.lower()
    # Try exact match first
    if name_lower in name_to_class:
        return name_to_class[name_lower], name_to_category[name_lower]
    
    # Try removing common modifiers
    base_name = name_lower.split('/')[0].strip()
    if base_name in name_to_class:
        return name_to_class[base_name], name_to_category[base_name]
    
    return None, None

# Update the dataframe
df_updated = df_completed.copy()

# Initialize counters
updated_count = 0
missing_count = 0
validation_issues = []

# Process each row
for idx, row in df_updated.iterrows():
    atc_code = row['ATC_CODE']
    antibiotic_name = row['ANTIMICROBIAL']
    
    # Try to get class and category by ATC code first
    antimicrobial_class = atc_to_class.get(atc_code)
    aware_category = atc_to_category.get(atc_code)
    
    # If not found by ATC code, try by name
    if not antimicrobial_class or not aware_category:
        class_by_name, category_by_name = find_matching_antibiotic(antibiotic_name)
        antimicrobial_class = antimicrobial_class or class_by_name
        aware_category = aware_category or category_by_name
    
    # Update the row
    if antimicrobial_class or aware_category:
        if pd.isna(df_updated.at[idx, 'ANTIMICROBIAL_CLASS']):
            df_updated.at[idx, 'ANTIMICROBIAL_CLASS'] = antimicrobial_class
        if pd.isna(df_updated.at[idx, 'WHO_AWARE_CLASSIFICATION']):
            df_updated.at[idx, 'WHO_AWARE_CLASSIFICATION'] = aware_category
        updated_count += 1
    else:
        missing_count += 1
        validation_issues.append(f"No match found for: {antibiotic_name} (ATC: {atc_code})")

# Print summary
print("\n=== Update Summary ===")
print(f"Total antimicrobials processed: {len(df_updated)}")
print(f"Successfully updated: {updated_count}")
print(f"Missing information: {missing_count}")

# Show sample of updated data
print("\n=== Sample of Updated Data ===")
display(df_updated.head())

# Show validation issues
if validation_issues:
    print("\n=== Validation Issues ===")
    for issue in validation_issues[:10]:
        print(issue)
    if len(validation_issues) > 10:
        print(f"...and {len(validation_issues) - 10} more issues")

# Save updated data
output_file = 'C:\\Personal_Projects\\Astro\\project_resources\\Completed_Data_Tables_withVersions\\Antimicrobials_with_ATC_COMPLETE_AWARE.xlsx'
df_updated.to_excel(output_file, index=False)
print(f"\nUpdated data saved to: {output_file}")

# Create summary of AWARE classifications
print("\n=== AWARE Classification Distribution ===")
print(df_updated['WHO_AWARE_CLASSIFICATION'].value_counts())

print("\n=== Antimicrobial Classes Distribution ===")
print(df_updated['ANTIMICROBIAL_CLASS'].value_counts().head(10))
print(f"...and {len(df_updated['ANTIMICROBIAL_CLASS'].value_counts()) - 10} more classes")

=== Update Summary ===
Total antimicrobials processed: 392
Successfully updated: 199
Missing information: 193

=== Sample of Updated Data ===

C:\Users\MAdu\AppData\Local\Temp\ipykernel_42156\1136951177.py:47: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Aminoglycosides' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_updated.at[idx, 'ANTIMICROBIAL_CLASS'] = antimicrobial_class
C:\Users\MAdu\AppData\Local\Temp\ipykernel_42156\1136951177.py:49: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Access' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_updated.at[idx, 'WHO_AWARE_CLASSIFICATION'] = aware_category

,ATC_CODE,WHONET_CODE,ANTIMICROBIAL,ANTIMICROBIAL_CLASS,WHO_AWARE_CLASSIFICATION
0,NaN,FCT,5-Fluorocytosine,NaN,NaN
1,NaN,ACM,Acetylmidecamycin,NaN,NaN
2,NaN,ASP,Acetylspiramycin,NaN,NaN
3,D06AX12,AMK,Amikacin,Aminoglycosides,Access
4,D06AX12,AKF,Amikacin/Fosfomycin,Aminoglycosides,Access

=== Validation Issues ===
No match found for: 5-Fluorocytosine (ATC: nan)
No match found for: Acetylmidecamycin (ATC: nan)
No match found for: Acetylspiramycin (ATC: nan)
No match found for: Amphotericin B (ATC: A01AB04)
No match found for: Amprolium (ATC: nan)
No match found for: Anidulafungin (ATC: J02AX06)
No match found for: Apalcillin (ATC: nan)
No match found for: Apramycin (ATC: nan)
No match found for: Astromicin (ATC: nan)
No match found for: Avibactam (ATC: nan)
...and 183 more issues

Updated data saved to: C:\Personal_Projects\Astro\project_resources\Completed_Data_Tables_withVersions\Antimicrobials_with_ATC_COMPLETE_AWARE.xlsx

=== AWARE Classification Distribution ===
WHO_AWARE_CLASSIFICATION
Watch      130
Access      45
Reserve     23
Watch        1
Name: count, dtype: int64

=== Antimicrobial Classes Distribution ===
ANTIMICROBIAL_CLASS
Third-generation-cephalosporins     23
Fluoroquinolones                    22
Penicillins                         18
Aminoglycosides                     16
Second-generation-cephalosporins    14
Macrolides                          13
Carbapenems                         11
Penicillins                          9
First-generation-cephalosporins      8
Fourth-generation-cephalosporins     8
Name: count, dtype: int64
...and 24 more classes

In [15]:
# Perform data quality checks
print("\n=== Data Quality Checks ===")

# Check for missing values
print("\nMissing values in each column:")
print(df_updated.isna().sum())

# Check unique values in WHO_AWARE_CLASSIFICATION
print("\nUnique WHO AWARE Classifications:")
print(df_updated['WHO_AWARE_CLASSIFICATION'].unique())

# Verify ATC code format
def is_valid_atc(code):
    if pd.isna(code):
        return False
    return bool(re.match(r'^[A-Z][0-9]{2}[A-Z]{2}[0-9]{2}$', str(code)))

invalid_atc = df_updated[~df_updated['ATC_CODE'].apply(lambda x: is_valid_atc(x) if pd.notna(x) else True)]
if not invalid_atc.empty:
    print("\nInvalid ATC codes found:")
    print(invalid_atc[['ANTIMICROBIAL', 'ATC_CODE']])

# Compare with WHO EML data
print("\nMatching statistics with WHO EML data:")
matched_atc = df_updated['ATC_CODE'].isin(df_who_eml_clean['ATC_code'])
print(f"ATC codes matched with WHO EML: {matched_atc.sum()} out of {len(df_updated)}")

# Save validation report
validation_report = f"""Validation Report ({pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')})

Total antimicrobials: {len(df_updated)}
Successfully matched: {updated_count}
Missing information: {missing_count}

Missing values by column:
{df_updated.isna().sum()}

WHO AWARE Classification distribution:
{df_updated['WHO_AWARE_CLASSIFICATION'].value_counts()}

Validation issues:
{chr(10).join(validation_issues)}
"""

validation_file = 'C:\\Personal_Projects\\Astro\\project_resources\\Completed_Data_Tables_withVersions\\validation_report.txt'
with open(validation_file, 'w') as f:
    f.write(validation_report)

print(f"\nDetailed validation report saved to: {validation_file}")

=== Data Quality Checks ===

Missing values in each column:
ATC_CODE                    142
WHONET_CODE                   0
ANTIMICROBIAL                 0
ANTIMICROBIAL_CLASS         193
WHO_AWARE_CLASSIFICATION    193
dtype: int64

Unique WHO AWARE Classifications:
[nan 'Access' 'Watch' 'Reserve' 'Watch ']

Matching statistics with WHO EML data:
ATC codes matched with WHO EML: 179 out of 392

Detailed validation report saved to: C:\Personal_Projects\Astro\project_resources\Completed_Data_Tables_withVersions\validation_report.txt

In [16]:
# Clean up WHO AWARE Classification values
df_updated['WHO_AWARE_CLASSIFICATION'] = df_updated['WHO_AWARE_CLASSIFICATION'].str.strip()

# Save final version
final_output = 'C:\\Personal_Projects\\Astro\\project_resources\\Completed_Data_Tables_withVersions\\Antimicrobials_with_ATC_COMPLETE_AWARE_FINAL.xlsx'
df_updated.to_excel(final_output, index=False)

print("=== Final Data Summary ===")
print("\nWHO AWARE Classifications (after cleanup):")
print(df_updated['WHO_AWARE_CLASSIFICATION'].value_counts(dropna=False))

print("\nTop 10 Antimicrobial Classes:")
print(df_updated['ANTIMICROBIAL_CLASS'].value_counts().head(10))

=== Final Data Summary ===

WHO AWARE Classifications (after cleanup):
WHO_AWARE_CLASSIFICATION
NaN        193
Watch      131
Access      45
Reserve     23
Name: count, dtype: int64

Top 10 Antimicrobial Classes:
ANTIMICROBIAL_CLASS
Third-generation-cephalosporins     23
Fluoroquinolones                    22
Penicillins                         18
Aminoglycosides                     16
Second-generation-cephalosporins    14
Macrolides                          13
Carbapenems                         11
Penicillins                          9
First-generation-cephalosporins      8
Fourth-generation-cephalosporins     8
Name: count, dtype: int64

In [19]:
import os

# Get total count and count of ATC codes
total_antimicrobials = len(df_updated)
atc_code_count = df_updated['ATC_CODE'].notna().sum()

print(f"Total number of antimicrobials: {total_antimicrobials}")
print(f"Number of antimicrobials with ATC codes: {atc_code_count}")
print(f"Percentage with ATC codes: {(atc_code_count/total_antimicrobials*100):.1f}%")

# Final cleanup and save
# Replace empty cells with "NA"
df_updated.fillna("NA", inplace=True)

# Create directory if it doesn't exist
output_dir = 'C:\\Personal_Projects\\Astro\\project_resources\\Data_Finished'
os.makedirs(output_dir, exist_ok=True)

# Save final dataset
output_file = os.path.join(output_dir, 'Antimicrobials_Data.csv')
df_updated.to_csv(output_file, index=False)
print(f"Final dataset saved to: {output_file}")

Total number of antimicrobials: 392
Number of antimicrobials with ATC codes: 250
Percentage with ATC codes: 63.8%
Final dataset saved to: C:\Personal_Projects\Astro\project_resources\Data_Finished\Antimicrobials_Data.csv